### ISSUE TITLE
please make deploy to heroku button

### ISSUE THREAD

**Issue by branchmaster** [fawazahmed0/quran-videos#50]
Hi Fawaz Ahmed , 
at the first tell you ajrokom indallah ,
ramazan mubarak , 
please if it's possible make deploy to heroku button with easy set config vars on it for easily deploy to free dyno without monthly fee.
waiting for your response
finest regards

**Comment by fawazahmed0** [comment]
salam Alaikum,
This project doesn't use heroku, it uses GitHub Actions (which is also free to use)
May I ask you what would you like to do, so that I can help you out?

**Comment by branchmaster** [comment]
aleykom salam brother ,
please help me how to make my own build with persian subtitle append using github actions?
I'm not have any knowledge about launch on github actions
ajrokom indallah

**Comment by fawazahmed0** [comment]
If you would like to upload video on your youtube channel, then you can do this way:
1. Fork my repo
2. I will create a PR in your forked repo, so that it can start working
3. Go to settings -> secrets and create three variables:
USER - (your youtube email)
KEY = (your youtube password)
RECOVERY = (your youtube recovery email, optional, but highly recommended)

**Comment by fawazahmed0** [comment]
> 
> 
> aleykom salam brother ,
> please help me how to make my own build with persian subtitle append using github actions?
> I'm not have any knowledge about launch on github actions
> ajrokom indallah

I already uploaded persian, if you want, you can get it from here:
https://www.youtube.com/watch?v=sWdmshYFOio&list=PLGZVnOdc8OJ-MduCMjnSEsrCAjWa2uiH3
you can download and reupload the videos if you want

**Comment by branchmaster** [comment]
okey , thanks for your response but more question , 
1 - your persian playlist update every one hour correctly without break , if answer yes , I can use that in own channel .
2 - if any tips can fork github action on android devices please tell me
finest regards

**Comment by fawazahmed0** [comment]
> 1 - your persian playlist update every one hour correctly without break
Sorry, Could you reframe this question?, I did not understand what you mean

**Comment by branchmaster** [comment]
no problem bro , 
i ask you this persian playlist you uploaded in your channel is automate work , or only for see results in action ?
it automate i can re-upload it on from this playlist at all.means persian subs upload continius permanent lifetime in this linked playlist ?

**Comment by fawazahmed0** [comment]
It's suhur time now, I will get back to you after Fajr Inshallah 👍

**Comment by branchmaster** [comment]
one more question I'm so interested to make my autopilot upload videos to my channel using my android phobe or any free dynos like heroku , netlify , repl.it or any way can auto encode persian videos on my own channel using phone ?

**Comment by fawazahmed0** [comment]
> 
> 
> one more question I'm so interested to make my autopilot upload videos to my channel using my android phone or any free dynos like heroku , netlify , repl.it or any way can auto encode persian videos on my own channel using phone ?

I have created a [PR](https://github.com/branchmaster/quran-videos/pull/1) , you can merge it and follow the steps in the PR, after that you will have automatic video uploads

**Comment by fawazahmed0** [comment]
You will also need to enable Github Actions in your fork repo, so that automatic video uploads can start.

Go to Settings of your forked repo -> Actions -> Choose `Allow all actions` and click Save button

![Screenshot (99)](https://user-images.githubusercontent.com/20347013/116274983-c9f7d380-a7a0-11eb-82c8-7f4446299275.png)

**Comment by branchmaster** [comment]
hi fawaz , 
ajrokom maghbool indalah,
I'm going exact the same steps you tell me but not make upload any video at the time reply writing. tell you what i do :
first go to your pr patch link & merged it , then go to my repo forked ,setting secrets & add 3 var same as your tips , then go to action & action permission default set on allow all actions then do nothing.
waiting for your response

**Comment by fawazahmed0** [comment]
> 
> 
> hi fawaz ,
> ajrokom maghbool indalah,
> 
> 1 - I'm going exact the same steps you tell me but not make upload any video at the time reply writing. tell you what i do :
> first go to your pr patch link & merged it , then go to my repo forked ,setting secrets & add 3 var same as your tips , then go to action & action permission default set on allow all actions then do nothing.
> 
> 2-how to increase number of upload videos per day , like 3 time per day ?
> waiting for your response

It will start from tomorrow at 1:00 am UTC Time
If it doesn't start tomorrow, then give me access to your fork, so that I can see why it's not working
You can give access by settings -> Manage access -> Invite collaborator

![Screenshot (100)](https://user-images.githubusercontent.com/20347013/116312096-a09f6d80-a7c9-11eb-80d7-542218522673.png)

**Comment by branchmaster** [comment]
hello again fawaz ,
it doesn't start today , I promoted you as collaborator.
please check what's wrong
finest regards

**Comment by fawazahmed0** [comment]
Can you give me the link to your youtube channel, so that I can see the videos have started to upload

**Comment by fawazahmed0** [comment]
And also go to this [link](https://myaccount.google.com/security) and see the recovery email and enter the correct recovery in Github secrets

**Comment by fawazahmed0** [comment]
Go to this [link](https://myaccount.google.com/security) and Delete recovery phone from your google settings, so that the program can login and start uploading the videos

**Comment by fawazahmed0** [comment]
Go to this [link](https://www.youtube.com/upload) and it should look like this:
![Screenshot (104)](https://user-images.githubusercontent.com/20347013/116501078-8fd82000-a8cd-11eb-8521-0d7771b232ca.png)

If it doesn't you might need to switch to studio or something, just make sure that when you open the above link it should look like the above picture, the program only uploads videos when it sees the above page

**Comment by branchmaster** [comment]
hi fawaz .
I can't access on pc because my personal system graphic card is on problem,
but in my android phone browser in desktop mode going to your link & after get attention about welcome to youtube studio , i get upload button like attach file.
![Screenshot_20210429-140618](https://user-images.githubusercontent.com/82944214/116531991-c0a85d00-a8ad-11eb-9dd3-774910bef359.jpg)
is it true ?

**Comment by fawazahmed0** [comment]
Try checking in PC, or try using this option https://www.cnet.com/how-to/how-to-request-desktop-version-of-a-web-site-in-chrome-for-android/ , it should see like my screenshot

**Comment by branchmaster** [comment]
hi fawaz ,
I'm testing with new youtube account & change github secrets correctly. but not work :(

**Comment by fawazahmed0** [comment]
Please share the user and password of your new youtube account at my email: fawazahmed0@hotmail.com

You can change the password, after the all the problems get fixed

**Comment by fawazahmed0** [comment]
Also share the recovery email

**Comment by branchmaster** [comment]
hi fawaz , 
shared succed , check your inbox.
finest regards

**Comment by fawazahmed0** [comment]
Alhumdulillah the uploading has started, it will take 2-3 days before whole quran gets uploaded.
Do you want to only upload 3 videos per day or whole parsi quran videos in 2-3 days?

**Comment by branchmaster** [comment]
shokranlillah , special thanks to you my brother , ajrokom mahfooz indallah , bro please set daily upload video count to 3 & set videos description as github secret or environment or help me where to change it.
waiting for your response
finest regards

**Comment by fawazahmed0** [comment]
> 
> 
> shokranlillah , special thanks to you my brother , ajrokom mahfooz indallah , bro please set daily upload parsi quran video count to 3 & set videos description as github secret or environment or help me where to change it.
> waiting for your response
> finest regards
ok, I will set to 3 video upload perday
You will have to edit video description manually from YouTube for each video

**Comment by branchmaster** [comment]
ok , special thanks for you , insha'Allah god protect you & your family . regards , mohamad
