### ISSUE TITLE
PR patch fail in action from yesterday

### ISSUE THREAD

**Issue by branchmaster** [fawazahmed0/quran-videos#53]
salamon alaykom fawaz ,
my uploaded videos from yesterday have hardsub caption & video title in english but older than this time all videos have persian hard sub caption & title. please check what commit branch or any other reason doing this problem .
mychannel url is : https://youtube.com/channel/UCwwA2OJytVk8mtkv3JoAkfw
waiting for your response
finest regards

**Comment by fawazahmed0** [comment]
you can delete the english videos, I have stopped the program

the work is complete as all the persian quran videos are uploaded in your youtube channel 👍

**Comment by raisedhand** [comment]
hello again fawaz , 
please don't stop the upload session ,
i can archive all others then please don't stop upload other languages.
waiting for your response
finesr regards
